<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWindowsForms>false</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>PreviewIcons</AssemblyName>
    <RootNamespace>PreviewIcons</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\IconFactory.cs" Link="IconFactory.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.7" />
  </ItemGroup>

</Project>
